services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
      - POSTGRES_DB=demo
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 2s
      retries: 5

  veggies:
    image: localhost/quarkus-observability-vegetable:latest
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/demo
      - DATABASE_USER=demo
      - DATABASE_PASSWORD=demo
    depends_on:
      db:
        condition: service_healthy

