services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=changeit
      - POSTGRES_DB=test
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 1s
      timeout: 2s
      retries: 5

  veggies:
    image: localhost/quarkus-observability-openshift:latest
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/demo
    depends_on:
      db:
        condition: service_healthy

