name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 🔹 Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # 🔹 Set up JDK for Quarkus build
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 🔹 Cache Maven dependencies for faster builds
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      # 🔹 Build Quarkus application
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 🔹 Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # 🔹 Build Docker image
      - name: Build Docker Image
        run: |
          docker build -f src/main/docker/Dockerfile.jvm -t ghcr.io/brunobat/quarkus-observability-openshift/app:latest .

      # 🔹 Push Docker image
      - name: Push Docker Image
        run: |
          docker push ghcr.io/brunobat/quarkus-observability-openshift/app:latest
